apiVersion: v1
kind: ConfigMap
metadata:
  name: well-known-jwks-config
data:
  jwks.json: |
    {
        "keys": [
            {
                "alg": "RS256",
                "e": "AQAB",
                "kid": "reissuer",
                "kty": "RSA",
                "n": "{{ JWKS_N }}",
                "use": "sig"
            }
        ]
    }
