repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==24.3.0]
        args: [-l, '79', -t, py312]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        additional_dependencies:
          - '@babel/eslint-parser@7.24.1'
          - '@babel/preset-react@7.24.1'
          - eslint@8.57.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@9.0.0
          - eslint-config-wesbos@3.2.3
          - eslint-plugin-html@8.1.1
          - eslint-plugin-import@2.29.1
          - eslint-plugin-jsx-a11y@6.8.0
          - eslint-plugin-prettier@4.2.1
          - eslint-plugin-react@7.34.0
          - eslint-plugin-react-hooks@4.6.0
          - prettier@2.8.8
