repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.6.0]
        args: [-l, '79', -t, py39]

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.22.0
    hooks:
      - id: eslint
        additional_dependencies:
          - '@babel/eslint-parser@7.18.9'
          - '@babel/preset-react@7.18.6'
          - eslint@8.22.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@8.5.0
          - eslint-config-wesbos@3.0.2
          - eslint-plugin-html@6.2.0
          - eslint-plugin-import@2.26.0
          - eslint-plugin-jsx-a11y@6.6.1
          - eslint-plugin-prettier@4.2.1
          - eslint-plugin-react@7.30.1
          - eslint-plugin-react-hooks@4.6.0
          - prettier@2.7.1
