repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter
        name: Check rST
        files: (README\.rst)|(CHANGELOG\.rst)

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        additional_dependencies:
          - toml

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
        args: [-l, '79', -t, py38]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.0.1
    hooks:
      - id: eslint
        additional_dependencies:
          - "@babel/eslint-parser@7.16.0"
          - "eslint@8.2.0"
          - "eslint-config-airbnb@18.2.1"
          - "eslint-config-prettier@8.3.0"
          - "eslint-config-wesbos@2.1.0"
          - "eslint-plugin-html@6.2.0"
          - "eslint-plugin-import@2.25.2"
          - "eslint-plugin-jsx-a11y@6.4.1"
          - "eslint-plugin-prettier@4.0.0"
          - "eslint-plugin-react@7.26.1"
          - "eslint-plugin-react-hooks@4.2.0"
          - "prettier@2.4.1"
