repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.1a1]
        args: [-l, '79', -t, py311]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.2.3
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml]
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.32.0
    hooks:
      - id: eslint
        additional_dependencies:
          - '@babel/eslint-parser@7.19.1'
          - '@babel/preset-react@7.18.6'
          - eslint@8.31.0
          - eslint-config-airbnb@19.0.4
          - eslint-config-prettier@8.5.0
          - eslint-config-wesbos@3.2.0
          - eslint-plugin-html@7.1.0
          - eslint-plugin-import@2.26.0
          - eslint-plugin-jsx-a11y@6.6.1
          - eslint-plugin-prettier@4.2.1
          - eslint-plugin-react@7.31.11
          - eslint-plugin-react-hooks@4.6.0
          - prettier@2.8.2
