# Run Redis for testing with a local development server.  This is used by
# tox -e run, which starts jwt_authorizer in the foreground.

version: "3"
services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
