apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jwt-authorizer
  name: jwt-authorizer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jwt-authorizer
  template:
    metadata:
      labels:
        k8s-app: jwt-authorizer
    spec:
      containers:
      - image: lsstdm/jwt_authorizer:stable
        imagePullPolicy: Always
        name: jwt-authorizer
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: jwt-authorizer
          mountPath: "/etc/jwt-authorizer"
          readOnly: true
      volumes:
      - name: jwt-authorizer
        secret:
          secretName: jwt-authorizer-config
