apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - image: lsstdm/oauth2_proxy:oidc
        imagePullPolicy: Always
        name: oauth2-proxy
        args:
        - -provider=oidc
        - -oidc-issuer-url=https://cilogon.org
        - -email-domain=*
        - -cookie-secure=true
        - -upstream=http://lsst-jwt-authorizer.lsst-pdac.svc.cluster.local:8080/
        - -http-address=0.0.0.0:4180
        - -set-xauthrequest
        - -cookie-refresh=10m
        - -pass-access-token
        - -pass-refresh-token
        - -pass-user-headers
        - -pass-id-token
        - -skip-jwt-bearer
        - -jwt-bearer-verifiers=https://cilogon.org
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: cilogon:/client_id/6ca7b54ac075b65bccb9c885f9ba4a75
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: lsst-lsp-int-oauth2
              key: client_secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: lsst-lsp-int-oauth2
              key: cookie_secret
        ports:
        - containerPort: 4180
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
      # 
spec:
  rules:
  - host: lsst-lsp-int.ncsa.illinois.edu
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - lsst-lsp-int.ncsa.illinois.edu
    secretName: tls-certificate-lsp-int
