name: CI

"on": [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - 3.8
          - 3.9
        database:
          - SQLite
          - PostgreSQL

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}

      # First try to restore the fully-installed node modules.  If that
      # works (no changes to the JavaScript layer), skip npm i and
      # restoring the cache of downloaded modules.  If that fails, restore
      # the cache of the downloaded modules and then run npm
      # clean-install.
      - name: Cache installed Node modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: ./ui/node_modules
          key: node-${{ steps.node_version.outputs.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache downloaded Node.js modules
        uses: actions/cache@v2
        if: steps.node-cache.outputs.cache-hit != 'true'
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install Node dependencies
        run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
        working-directory: ./ui

      # This has to happen after installing Node modules because we run
      # eslint and it wants react to be already installed.
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.0
        if: matrix.database == 'SQLite'

      - name: Build the UI
        run: npm run build
        working-directory: ./ui

      - name: Install tox
        run: pip install tox tox-docker

      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v2
        with:
          path: .tox
          # requirements/*.txt and tox.ini have versioning or dependency
          # information that would impact the tox environment.
          key: tox-${{ matrix.python }}-${{ hashFiles('requirements/*.txt') }}-${{ hashFiles('tox.ini') }}
          restore-keys: |
            tox-${{ matrix.python }}-${{ hashFiles('requirements/*.txt') }}-

      - name: Run tox (SQLite)
        run: tox -e py,coverage-report,typing
        if: matrix.database == 'SQLite'

      - name: Run tox (PostgreSQL)
        run: tox -e docker
        if: matrix.database == 'PostgreSQL'
