# This is a separate run of the Python test suite that doesn't cache
# the tox environment and runs from a schedule.  The purpose is to test
# compatibility with the latest versions of all modules neophile
# depends on, since neophile (being a PyPI application) does not pin
# its dependencies.

name: Periodic CI

"on":
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python:
          - "3.11"

    steps:
      - uses: actions/checkout@v3

      # Use the oldest supported version of Python to update dependencies,
      # not the matrixed Python version, since this accurately reflects
      # how dependencies should later be updated.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install neophile
        run: pip install neophile

      - name: Run neophile
        run: neophile update

      - name: Update package lists
        run: sudo apt-get update

      - name: Install extra packages
        run: sudo apt install -y graphviz libpq-dev libldap2-dev libsasl2-dev

      - name: Run tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "lint,typing,py,docs,docs-linkcheck"

      - name: Report status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "Periodic test for {repo} failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK }}
